name = "y-router"
main = "index.ts"
compatibility_date = "2025-05-30"
routes = [
  { pattern = "cc.yovy.app", custom_domain = true }
]

# Enable logging
[observability]
enabled = true
head_sampling_rate = 1
